name: Frontend CI

on:
  push:
    paths:
      - "webapp-frontend/**"
  pull_request:
    paths:
      - "webapp-frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
